### ISSUE TITLE
make doc fails

### ISSUE THREAD

**Issue by rgs1** [nickel-org/nickel.rs#144]
With nightly:

```shell
$ make doc
...
rustdoc -L target/deps src/lib.rs
src/lib.rs:27:1: 27:18 error: multiple matching crates for `log`
src/lib.rs:27 extern crate log;
              ^~~~~~~~~~~~~~~~~
note: candidates:
note: path: /usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-4e7c5e5c.so
note: path: /usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-4e7c5e5c.rlib
note: crate name: log
note: path: /home/rgs/src/rust/nickel.rs/target/deps/liblog-6ccd07f1f8244a62.rlib
note: crate name: log
src/lib.rs:27:1: 27:18 error: can't find crate for `log`
src/lib.rs:27 extern crate log;
              ^~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
thread '<unnamed>' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:151
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "rustc failed"', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:743
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:362
Makefile:14: recipe for target 'doc' failed
make: *** [doc] Error 101
```

Ideas?

**Comment by Ryman** [comment]
`cargo clean`?

**Comment by rgs1** [comment]
Still fails for me - works for you?

**Comment by Ryman** [comment]
The referenced issue actually has a fix for this issue, but we're only passing -L and not forcing externs, so it still doesn't know which crate to use for log. If we passed externs then things *should* now be fine, but it's simpler to just use cargo to do this for us.
